version: "3.8"
services:
  testdataloader:
    container_name: testdataloader
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000
      - 9230:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
networks:
  webnet:
